version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-ionicons
    versions:
    - 3.1.4
    - 4.0.2
    - 4.1.0
  - dependency-name: react-toastify
    versions:
    - 7.0.1
    - 7.0.2
    - 7.0.3
  - dependency-name: lodash-es
    versions:
    - 4.17.20
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
